import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.decisions': 'Decision Queue',
    'nav.control': 'Control Panel',
    'nav.creatives': 'Creatives',
    'nav.saturation': 'Saturation',
    'nav.opportunities': 'Opportunities',
    'nav.policies': 'Policies',
    'nav.audit': 'Audit Log',
    'nav.help': 'Help & Tutorial',
    'nav.settings': 'Settings',
    'nav.brain': 'Operator Brain',
    'nav.ops': 'Ops Console',
    'nav.analytics': 'Analytics',
    'nav.alerts': 'Alert Center',
    'nav.contentStudio': 'Content Studio',
    'nav.brandProfile': 'Brand Profile',

    // Onboarding
    'onboarding.welcome_title': 'Welcome to Renaissance',
    'onboarding.welcome_desc': 'Let\'s get your ad account connected and optimized in just a few minutes.',
    'onboarding.get_started': 'Get Started',
    'onboarding.connect_title': 'Connect Your Meta Account',
    'onboarding.connect_desc': 'Link your Facebook/Instagram advertising account to start syncing campaigns and insights.',
    'onboarding.connect_meta_btn': 'Connect Meta Account',
    'onboarding.skip_for_now': 'Skip for now',
    'onboarding.select_title': 'Select Ad Account',
    'onboarding.select_desc': 'Choose which ad account you want to manage.',
    'onboarding.no_accounts': 'No ad accounts found. You can add one later from the Control Panel.',
    'onboarding.no_templates': 'No templates available yet. You can configure one later.',
    'onboarding.template_title': 'Choose Your Template',
    'onboarding.template_desc': 'Select a template that matches your business vertical for optimized defaults.',
    'onboarding.configure_title': 'Review Configuration',
    'onboarding.configure_desc': 'Your template has been applied. You can customize these settings later.',
    'onboarding.config_ready': 'Configuration is ready with optimized defaults for your vertical.',
    'onboarding.continue': 'Continue',
    'onboarding.complete_title': 'You\'re All Set!',
    'onboarding.complete_desc': 'Your account is being synced. You\'ll see your campaigns and insights shortly.',
    'onboarding.syncing_data': 'Syncing your data...',
    'onboarding.go_to_dashboard': 'Go to Dashboard',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Performance insights from your real campaign data',
    'analytics.total_spend': 'Total Spend',
    'analytics.avg_ctr': 'Avg CTR',
    'analytics.avg_cpc': 'Avg CPC',
    'analytics.avg_roas': 'Avg ROAS',
    'analytics.conversions': 'Conversions',
    'analytics.spend_over_time': 'Spend Over Time',
    'analytics.top_campaigns': 'Top Campaigns',
    'analytics.campaign': 'Campaign',
    'analytics.spend_col': 'Spend',
    'analytics.clicks': 'Clicks',
    'analytics.benchmarks': 'Benchmarks (vs 30-day baseline)',

    // Alert Center
    'alerts.title': 'Alert Center',
    'alerts.subtitle': 'Monitor and manage alerts from your campaigns',
    'alerts.critical': 'Critical',
    'alerts.high': 'High',
    'alerts.medium': 'Medium',
    'alerts.low': 'Low',
    'alerts.total': 'Total',
    'alerts.all_status': 'All Status',
    'alerts.all_severity': 'All Severity',
    'alerts.status_active': 'Active',
    'alerts.status_ack': 'Acknowledged',
    'alerts.status_resolved': 'Resolved',
    'alerts.status_snoozed': 'Snoozed',
    'alerts.entity': 'Entity',
    'alerts.payload': 'Payload',
    'alerts.acknowledge': 'Acknowledge',
    'alerts.resolve': 'Resolve',
    'alerts.snooze': 'Snooze',

    // Ops Console
    'ops.title': 'Ops Console',
    'ops.subtitle': 'Job monitoring, provider health, and queue statistics',
    'ops.queues': 'Queue Statistics',
    'ops.providers': 'Provider Health',
    'ops.jobs': 'Job Runs',
    'ops.pending': 'Pending',
    'ops.running': 'Running',
    'ops.failed': 'Failed',
    'ops.circuit': 'Circuit',
    'ops.rate_limit': 'Rate Limit',
    'ops.retry': 'Retry',
    'ops.cancel': 'Cancel',
    'ops.job_detail': 'Job Detail',
    'ops.filter_status': 'Filter by status',
    'ops.filter_type': 'Filter by type',
    'ops.all': 'All',

    // Brain
    'brain.title': 'Operator Brain',
    'brain.subtitle': 'AI learning insights — features, outcomes, and entity trust',
    'brain.top_features': 'Top Performing Features',
    'brain.recent_outcomes': 'Recent Outcomes',
    'brain.entity_trust': 'Entity Trust Status',
    'brain.win_rate': 'Win Rate',
    'brain.samples': 'Samples',
    'brain.trust': 'Trust',
    'brain.smart_order': 'Smart Order',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your Meta Ads performance',
    'dashboard.pending': 'Pending Decisions',
    'dashboard.approved': 'Approved This Week',
    'dashboard.executed': 'Actions Executed',

    // Control Panel
    'control.title': 'Control Panel',
    'control.subtitle': 'Create manual decision drafts and manage settings',
    'control.operator_armed': 'Operator Armed',
    'control.operator_on': 'ON - Live executions enabled',
    'control.operator_off': 'OFF - Dry-run mode only (safe)',
    'control.operator_warning': 'Warning: Operator Armed is ON. Approved decisions can make REAL changes to your Meta Ads account.',
    'control.meta_connection': 'Meta Ads Connection',
    'control.meta_description': 'Connect your Facebook/Instagram advertising accounts',
    'control.connect_account': 'Connect Account',
    'control.action_config': 'Action Configuration',
    'control.action_type': 'Action Type',
    'control.budget_change': 'Budget Change',
    'control.adset_pause': 'Adset Pause',
    'control.creative_swap': 'Creative Swap',
    'control.entity_type': 'Entity Type',
    'control.entity_id': 'Entity ID',
    'control.entity_name': 'Entity Name',
    'control.budget_config': 'Budget Configuration',
    'control.current_budget': 'Current Budget (USD/day)',
    'control.new_budget': 'New Budget (USD/day)',
    'control.rationale': 'Rationale',
    'control.rationale_placeholder': 'Explain why this change is needed...',
    'control.cancel': 'Cancel',
    'control.create_draft': 'Create Draft',
    'control.reconnect': 'Reconnect',
    'control.connecting': 'Connecting...',
    'control.active_account': 'Active Ad Account',
    'control.select_account': 'Select an account...',
    'control.no_active': 'Connected but no active account selected',
    'control.connect_first': 'Connect a Meta Account',
    'control.connect_first_desc': 'You need to connect and select an active Meta ad account before creating decisions.',
    'control.meta_success': 'Meta connected successfully!',
    'control.accounts_found': 'ad account(s) found',

    // Creatives
    'creatives.title': 'Creative Library',
    'creatives.subtitle': 'AI-analyzed ad creatives with performance scores',
    'creatives.generate_new': 'Generate New',
    'creatives.visual_hook': 'Visual Hook',
    'creatives.emotional_score': 'Emotional Score',
    'creatives.brand_consistency': 'Brand Consistency',
    'creatives.use_in_campaign': 'Use in Campaign',

    // Saturation
    'saturation.title': 'Audience Saturation',
    'saturation.subtitle': 'Monitor audience fatigue and ad frequency',
    'saturation.frequency': 'Frequency',
    'saturation.saturation': 'Saturation',
    'saturation.recommendation': 'Recommendation',

    // Opportunities
    'opportunities.title': 'Market Opportunities',
    'opportunities.subtitle': 'AI-detected opportunities to scale your campaigns',
    'opportunities.priority': 'Priority',
    'opportunities.high': 'High',
    'opportunities.medium': 'Medium',
    'opportunities.low': 'Low',
    'opportunities.potential_impact': 'Potential Impact',
    'opportunities.create_campaign': 'Create Campaign',

    // Policies
    'policies.title': 'Policy Rules',
    'policies.subtitle': 'Automated rules and guardrails',
    'policies.enabled': 'Enabled',
    'policies.disabled': 'Disabled',
    'policies.critical': 'Critical',
    'policies.warning': 'Warning',
    'policies.info': 'Info',

    // Decisions
    'decisions.title': 'Decision Queue',
    'decisions.subtitle': 'Review and approve AI-recommended actions',
    'decisions.validate': 'Validate',
    'decisions.request_approval': 'Request Approval',
    'decisions.approve': 'Approve',
    'decisions.reject': 'Reject',
    'decisions.dry_run': 'Dry Run First',
    'decisions.execute_live': 'Execute Live',

    // Audit Log
    'audit.title': 'Audit Log',
    'audit.subtitle': 'Complete history of executed decisions',
    'audit.action': 'Action',
    'audit.entity': 'Entity',
    'audit.status': 'Status',
    'audit.dry_run': 'Dry Run',
    'audit.timestamp': 'Timestamp',

    // Dashboard Sprint 6
    'dashboard.sync_health': 'Sync Health',
    'dashboard.active_alerts': 'Active Alerts',
    'dashboard.campaigns': 'Campaigns',
    'dashboard.assets_lag': 'Assets Lag',
    'dashboard.insights_lag': 'Insights Lag',
    'dashboard.errors': 'Errors',
    'dashboard.campaign_name': 'Campaign',
    'dashboard.campaign_status': 'Status',
    'dashboard.campaign_objective': 'Objective',
    'dashboard.campaign_budget': 'Budget',

    // Radar / Competitive Intelligence
    'nav.radar': 'Competitive Radar',
    'nav.flywheel': 'Flywheel',
    'nav.dataRoom': 'Data Room',
    'nav.group.flywheel': 'Flywheel',
    'nav.group.intelligence': 'Intelligence',
    'nav.group.opportunities': 'Opportunities',
    'nav.group.create': 'Create',
    'nav.group.measure': 'Measure',
    'nav.group.ops': 'Ops',
    'nav.group.settings': 'Settings',
    'flywheel.title': 'Flywheel',
    'flywheel.subtitle': 'End-to-end optimization cycle',
    'flywheel.run_full': 'Run Full Cycle',
    'flywheel.stop': 'Stop',
    'flywheel.next_action': 'Next Best Action',
    'flywheel.step.meta_sync': 'Meta Sync',
    'flywheel.step.brain': 'Brain Analysis',
    'flywheel.step.saturation': 'Saturation Check',
    'flywheel.step.intelligence': 'Unified Intelligence',
    'flywheel.step.opportunities': 'Opportunities',
    'flywheel.step.creatives': 'Creatives',
    'flywheel.step.content': 'Content Studio',
    'flywheel.step.export': 'Export',
    'flywheel.no_runs': 'No flywheel runs yet. Start your first optimization cycle.',
    'flywheel.recent_runs': 'Recent Runs',
    'dataRoom.title': 'Data Room',
    'dataRoom.subtitle': 'Export all your data as XLSX for auditing and analysis',
    'dataRoom.export_xlsx': 'Export XLSX',
    'dataRoom.datasets': 'Datasets',
    'dataRoom.filters': 'Filters',
    'dataRoom.previous_exports': 'Previous Exports',
    'dataRoom.date_range': 'Date Range',
    'dataRoom.no_exports': 'No exports yet. Configure your export and click Export XLSX.',
    'empty.brain': 'Run Meta Sync first to populate Brain data',
    'empty.opportunities': 'Run Flywheel or Analyze to discover opportunities',
    'empty.creatives': 'Pick an Opportunity or run BrandMap to generate creatives',
    'radar.title': 'Competitive Radar',
    'radar.subtitle': 'Real-time competitive intelligence dashboard',
    'radar.competitors': 'Competitors',
    'radar.no_competitors': 'No competitors tracked yet',
    'radar.no_competitors_hint': 'Run a detection scan to discover competitors',
    'radar.tab_ads': 'New Ads',
    'radar.tab_offers': 'Offer Changes',
    'radar.tab_trends': 'Angle Trends',
    'radar.tab_search': 'Search',
    'radar.new_ads': 'New Ads Feed',
    'radar.no_ads': 'No new ads detected',
    'radar.offer_changes': 'Offer Changes',
    'radar.no_offers': 'No offer changes detected',
    'radar.angle_trends': 'Angle Trends',
    'radar.no_trends': 'No angle trends detected',
    'radar.search_placeholder': 'Search ads, offers, keywords...',
    'radar.no_results': 'No results found',
    'radar.no_results_hint': 'Try adjusting your search or filters',
    'radar.filter_all': 'All',
    'radar.filter_type': 'Type',
    'radar.filter_platform': 'Platform',
    'radar.filter_format': 'Format',
    'radar.filter_competitor': 'Competitor',
    'radar.filter_date_from': 'From',
    'radar.filter_date_to': 'To',
    'radar.similar_ads': 'Similar Ads',
    'radar.confidence': 'Confidence',
    'radar.impact': 'Impact',
    'radar.priority': 'Priority',
    'radar.first_seen': 'First Seen',
    'radar.last_seen': 'Last Seen',
    'radar.view_similar': 'View Similar',
    'radar.close': 'Close',
    'radar.load_more': 'Load More',
    'radar.run_scan': 'Run Scan',
    'radar.scanning': 'Scanning...',
    'radar.all_competitors': 'All Competitors',
    'radar.evidence': 'Evidence',
    'radar.actions': 'Suggested Actions',
    'radar.rationale': 'Rationale',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error loading data',
    'common.no_data': 'No data available',
    'common.success': 'Success',
    'common.failed': 'Failed',

    // Tutorial
    'tutorial.welcome': 'Welcome to Renaissance',
    'tutorial.start': 'Start Tutorial',
    'tutorial.skip': 'Skip Tutorial',
    'tutorial.next': 'Next',
    'tutorial.prev': 'Previous',
    'tutorial.finish': 'Finish',
    'tutorial.step': 'Step',
    'tutorial.of': 'of',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel Principal',
    'nav.decisions': 'Cola de Decisiones',
    'nav.control': 'Panel de Control',
    'nav.creatives': 'Creativos',
    'nav.saturation': 'Saturación',
    'nav.opportunities': 'Oportunidades',
    'nav.policies': 'Políticas',
    'nav.audit': 'Registro de Auditoría',
    'nav.help': 'Ayuda y Tutorial',
    'nav.settings': 'Configuración',
    'nav.brain': 'Cerebro del Operador',
    'nav.ops': 'Consola de Operaciones',
    'nav.analytics': 'Analíticas',
    'nav.alerts': 'Centro de Alertas',
    'nav.contentStudio': 'Content Studio',
    'nav.brandProfile': 'Perfil de Marca',

    // Onboarding
    'onboarding.welcome_title': 'Bienvenido a Renaissance',
    'onboarding.welcome_desc': 'Conectemos tu cuenta publicitaria y la optimicemos en solo unos minutos.',
    'onboarding.get_started': 'Comenzar',
    'onboarding.connect_title': 'Conecta Tu Cuenta de Meta',
    'onboarding.connect_desc': 'Vincula tu cuenta publicitaria de Facebook/Instagram para sincronizar campañas e insights.',
    'onboarding.connect_meta_btn': 'Conectar Cuenta Meta',
    'onboarding.skip_for_now': 'Saltar por ahora',
    'onboarding.select_title': 'Seleccionar Cuenta Publicitaria',
    'onboarding.select_desc': 'Elige qué cuenta publicitaria deseas gestionar.',
    'onboarding.no_accounts': 'No se encontraron cuentas publicitarias. Puedes agregar una luego desde el Panel de Control.',
    'onboarding.no_templates': 'No hay plantillas disponibles. Puedes configurar una más adelante.',
    'onboarding.template_title': 'Elige Tu Plantilla',
    'onboarding.template_desc': 'Selecciona una plantilla que coincida con tu vertical de negocio para ajustes optimizados.',
    'onboarding.configure_title': 'Revisar Configuración',
    'onboarding.configure_desc': 'Tu plantilla ha sido aplicada. Puedes personalizar estos ajustes después.',
    'onboarding.config_ready': 'La configuración está lista con ajustes optimizados para tu vertical.',
    'onboarding.continue': 'Continuar',
    'onboarding.complete_title': '¡Todo Listo!',
    'onboarding.complete_desc': 'Tu cuenta se está sincronizando. Verás tus campañas e insights en breve.',
    'onboarding.syncing_data': 'Sincronizando tus datos...',
    'onboarding.go_to_dashboard': 'Ir al Panel Principal',

    // Analytics
    'analytics.title': 'Analíticas',
    'analytics.subtitle': 'Insights de rendimiento de tus datos reales de campañas',
    'analytics.total_spend': 'Gasto Total',
    'analytics.avg_ctr': 'CTR Promedio',
    'analytics.avg_cpc': 'CPC Promedio',
    'analytics.avg_roas': 'ROAS Promedio',
    'analytics.conversions': 'Conversiones',
    'analytics.spend_over_time': 'Gasto en el Tiempo',
    'analytics.top_campaigns': 'Campañas Principales',
    'analytics.campaign': 'Campaña',
    'analytics.spend_col': 'Gasto',
    'analytics.clicks': 'Clics',
    'analytics.benchmarks': 'Benchmarks (vs promedio 30 días)',

    // Alert Center
    'alerts.title': 'Centro de Alertas',
    'alerts.subtitle': 'Monitorea y gestiona alertas de tus campañas',
    'alerts.critical': 'Crítica',
    'alerts.high': 'Alta',
    'alerts.medium': 'Media',
    'alerts.low': 'Baja',
    'alerts.total': 'Total',
    'alerts.all_status': 'Todos los Estados',
    'alerts.all_severity': 'Todas las Severidades',
    'alerts.status_active': 'Activa',
    'alerts.status_ack': 'Reconocida',
    'alerts.status_resolved': 'Resuelta',
    'alerts.status_snoozed': 'Pospuesta',
    'alerts.entity': 'Entidad',
    'alerts.payload': 'Datos',
    'alerts.acknowledge': 'Reconocer',
    'alerts.resolve': 'Resolver',
    'alerts.snooze': 'Posponer',

    // Ops Console
    'ops.title': 'Consola de Operaciones',
    'ops.subtitle': 'Monitoreo de jobs, salud de proveedores y estadísticas de colas',
    'ops.queues': 'Estadísticas de Colas',
    'ops.providers': 'Salud de Proveedores',
    'ops.jobs': 'Ejecuciones de Jobs',
    'ops.pending': 'Pendiente',
    'ops.running': 'Ejecutando',
    'ops.failed': 'Fallido',
    'ops.circuit': 'Circuit',
    'ops.rate_limit': 'Rate Limit',
    'ops.retry': 'Reintentar',
    'ops.cancel': 'Cancelar',
    'ops.job_detail': 'Detalle del Job',
    'ops.filter_status': 'Filtrar por estado',
    'ops.filter_type': 'Filtrar por tipo',
    'ops.all': 'Todos',

    // Brain
    'brain.title': 'Cerebro del Operador',
    'brain.subtitle': 'Inteligencia de aprendizaje — features, outcomes y confianza de entidades',
    'brain.top_features': 'Features con Mejor Rendimiento',
    'brain.recent_outcomes': 'Outcomes Recientes',
    'brain.entity_trust': 'Estado de Confianza',
    'brain.win_rate': 'Tasa de Victoria',
    'brain.samples': 'Muestras',
    'brain.trust': 'Confianza',
    'brain.smart_order': 'Orden Inteligente',

    // Dashboard
    'dashboard.title': 'Panel Principal',
    'dashboard.subtitle': 'Resumen del rendimiento de tus anuncios en Meta',
    'dashboard.pending': 'Decisiones Pendientes',
    'dashboard.approved': 'Aprobadas Esta Semana',
    'dashboard.executed': 'Acciones Ejecutadas',

    // Control Panel
    'control.title': 'Panel de Control',
    'control.subtitle': 'Crear borradores de decisiones manuales y gestionar configuraciones',
    'control.operator_armed': 'Operador Armado',
    'control.operator_on': 'ACTIVADO - Ejecuciones en vivo habilitadas',
    'control.operator_off': 'DESACTIVADO - Solo modo de prueba (seguro)',
    'control.operator_warning': 'Advertencia: Operador Armado está ACTIVADO. Las decisiones aprobadas pueden hacer cambios REALES en tu cuenta de Meta Ads.',
    'control.meta_connection': 'Conexión de Meta Ads',
    'control.meta_description': 'Conecta tus cuentas publicitarias de Facebook/Instagram',
    'control.connect_account': 'Conectar Cuenta',
    'control.action_config': 'Configuración de Acción',
    'control.action_type': 'Tipo de Acción',
    'control.budget_change': 'Cambio de Presupuesto',
    'control.adset_pause': 'Pausar Conjunto de Anuncios',
    'control.creative_swap': 'Cambio de Creativo',
    'control.entity_type': 'Tipo de Entidad',
    'control.entity_id': 'ID de Entidad',
    'control.entity_name': 'Nombre de Entidad',
    'control.budget_config': 'Configuración de Presupuesto',
    'control.current_budget': 'Presupuesto Actual (USD/día)',
    'control.new_budget': 'Nuevo Presupuesto (USD/día)',
    'control.rationale': 'Justificación',
    'control.rationale_placeholder': 'Explica por qué se necesita este cambio...',
    'control.cancel': 'Cancelar',
    'control.create_draft': 'Crear Borrador',
    'control.reconnect': 'Reconectar',
    'control.connecting': 'Conectando...',
    'control.active_account': 'Cuenta Activa',
    'control.select_account': 'Seleccionar una cuenta...',
    'control.no_active': 'Conectado pero sin cuenta activa seleccionada',
    'control.connect_first': 'Conectar una Cuenta Meta',
    'control.connect_first_desc': 'Necesitas conectar y seleccionar una cuenta activa de Meta Ads antes de crear decisiones.',
    'control.meta_success': 'Meta conectado exitosamente!',
    'control.accounts_found': 'cuenta(s) encontrada(s)',

    // Creatives
    'creatives.title': 'Biblioteca de Creativos',
    'creatives.subtitle': 'Creativos publicitarios analizados por IA con puntuaciones de rendimiento',
    'creatives.generate_new': 'Generar Nuevo',
    'creatives.visual_hook': 'Gancho Visual',
    'creatives.emotional_score': 'Puntuación Emocional',
    'creatives.brand_consistency': 'Consistencia de Marca',
    'creatives.use_in_campaign': 'Usar en Campaña',

    // Saturation
    'saturation.title': 'Saturación de Audiencia',
    'saturation.subtitle': 'Monitorear fatiga de audiencia y frecuencia de anuncios',
    'saturation.frequency': 'Frecuencia',
    'saturation.saturation': 'Saturación',
    'saturation.recommendation': 'Recomendación',

    // Opportunities
    'opportunities.title': 'Oportunidades de Mercado',
    'opportunities.subtitle': 'Oportunidades detectadas por IA para escalar tus campañas',
    'opportunities.priority': 'Prioridad',
    'opportunities.high': 'Alta',
    'opportunities.medium': 'Media',
    'opportunities.low': 'Baja',
    'opportunities.potential_impact': 'Impacto Potencial',
    'opportunities.create_campaign': 'Crear Campaña',

    // Policies
    'policies.title': 'Reglas de Política',
    'policies.subtitle': 'Reglas automatizadas y barreras de seguridad',
    'policies.enabled': 'Habilitado',
    'policies.disabled': 'Deshabilitado',
    'policies.critical': 'Crítico',
    'policies.warning': 'Advertencia',
    'policies.info': 'Información',

    // Decisions
    'decisions.title': 'Cola de Decisiones',
    'decisions.subtitle': 'Revisar y aprobar acciones recomendadas por IA',
    'decisions.validate': 'Validar',
    'decisions.request_approval': 'Solicitar Aprobación',
    'decisions.approve': 'Aprobar',
    'decisions.reject': 'Rechazar',
    'decisions.dry_run': 'Prueba Seca Primero',
    'decisions.execute_live': 'Ejecutar en Vivo',

    // Audit Log
    'audit.title': 'Registro de Auditoría',
    'audit.subtitle': 'Historial completo de decisiones ejecutadas',
    'audit.action': 'Acción',
    'audit.entity': 'Entidad',
    'audit.status': 'Estado',
    'audit.dry_run': 'Prueba Seca',
    'audit.timestamp': 'Fecha y Hora',

    // Dashboard Sprint 6
    'dashboard.sync_health': 'Estado de Sincronización',
    'dashboard.active_alerts': 'Alertas Activas',
    'dashboard.campaigns': 'Campañas',
    'dashboard.assets_lag': 'Retraso Assets',
    'dashboard.insights_lag': 'Retraso Insights',
    'dashboard.errors': 'Errores',
    'dashboard.campaign_name': 'Campaña',
    'dashboard.campaign_status': 'Estado',
    'dashboard.campaign_objective': 'Objetivo',
    'dashboard.campaign_budget': 'Presupuesto',

    // Radar / Competitive Intelligence
    'nav.radar': 'Radar Competitivo',
    'nav.flywheel': 'Flywheel',
    'nav.dataRoom': 'Sala de Datos',
    'nav.group.flywheel': 'Flywheel',
    'nav.group.intelligence': 'Inteligencia',
    'nav.group.opportunities': 'Oportunidades',
    'nav.group.create': 'Crear',
    'nav.group.measure': 'Medir',
    'nav.group.ops': 'Operaciones',
    'nav.group.settings': 'Configuración',
    'flywheel.title': 'Flywheel',
    'flywheel.subtitle': 'Ciclo de optimización de extremo a extremo',
    'flywheel.run_full': 'Ejecutar Ciclo Completo',
    'flywheel.stop': 'Detener',
    'flywheel.next_action': 'Siguiente Mejor Acción',
    'flywheel.step.meta_sync': 'Sincronizar Meta',
    'flywheel.step.brain': 'Análisis del Cerebro',
    'flywheel.step.saturation': 'Verificar Saturación',
    'flywheel.step.intelligence': 'Inteligencia Unificada',
    'flywheel.step.opportunities': 'Oportunidades',
    'flywheel.step.creatives': 'Creativos',
    'flywheel.step.content': 'Content Studio',
    'flywheel.step.export': 'Exportar',
    'flywheel.no_runs': 'No hay ejecuciones del flywheel aún. Inicia tu primer ciclo de optimización.',
    'flywheel.recent_runs': 'Ejecuciones Recientes',
    'dataRoom.title': 'Sala de Datos',
    'dataRoom.subtitle': 'Exporta todos tus datos como XLSX para auditoría y análisis',
    'dataRoom.export_xlsx': 'Exportar XLSX',
    'dataRoom.datasets': 'Conjuntos de Datos',
    'dataRoom.filters': 'Filtros',
    'dataRoom.previous_exports': 'Exportaciones Anteriores',
    'dataRoom.date_range': 'Rango de Fechas',
    'dataRoom.no_exports': 'No hay exportaciones aún. Configura tu exportación y haz clic en Exportar XLSX.',
    'empty.brain': 'Ejecuta Meta Sync primero para llenar datos del Cerebro',
    'empty.opportunities': 'Ejecuta Flywheel o Analizar para descubrir oportunidades',
    'empty.creatives': 'Elige una Oportunidad o ejecuta BrandMap para generar creativos',
    'radar.title': 'Radar Competitivo',
    'radar.subtitle': 'Panel de inteligencia competitiva en tiempo real',
    'radar.competitors': 'Competidores',
    'radar.no_competitors': 'No hay competidores rastreados aún',
    'radar.no_competitors_hint': 'Ejecuta un escaneo de detección para descubrir competidores',
    'radar.tab_ads': 'Nuevos Anuncios',
    'radar.tab_offers': 'Cambios de Oferta',
    'radar.tab_trends': 'Tendencias de Ángulos',
    'radar.tab_search': 'Buscar',
    'radar.new_ads': 'Feed de Nuevos Anuncios',
    'radar.no_ads': 'No se detectaron nuevos anuncios',
    'radar.offer_changes': 'Cambios de Oferta',
    'radar.no_offers': 'No se detectaron cambios de oferta',
    'radar.angle_trends': 'Tendencias de Ángulos',
    'radar.no_trends': 'No se detectaron tendencias de ángulos',
    'radar.search_placeholder': 'Buscar anuncios, ofertas, palabras clave...',
    'radar.no_results': 'Sin resultados',
    'radar.no_results_hint': 'Intenta ajustar tu búsqueda o filtros',
    'radar.filter_all': 'Todos',
    'radar.filter_type': 'Tipo',
    'radar.filter_platform': 'Plataforma',
    'radar.filter_format': 'Formato',
    'radar.filter_competitor': 'Competidor',
    'radar.filter_date_from': 'Desde',
    'radar.filter_date_to': 'Hasta',
    'radar.similar_ads': 'Anuncios Similares',
    'radar.confidence': 'Confianza',
    'radar.impact': 'Impacto',
    'radar.priority': 'Prioridad',
    'radar.first_seen': 'Visto por primera vez',
    'radar.last_seen': 'Última vez visto',
    'radar.view_similar': 'Ver Similares',
    'radar.close': 'Cerrar',
    'radar.load_more': 'Cargar Más',
    'radar.run_scan': 'Ejecutar Escaneo',
    'radar.scanning': 'Escaneando...',
    'radar.all_competitors': 'Todos los Competidores',
    'radar.evidence': 'Evidencia',
    'radar.actions': 'Acciones Sugeridas',
    'radar.rationale': 'Justificación',

    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error al cargar datos',
    'common.no_data': 'No hay datos disponibles',
    'common.success': 'Éxito',
    'common.failed': 'Fallido',

    // Tutorial
    'tutorial.welcome': 'Bienvenido a Renaissance',
    'tutorial.start': 'Iniciar Tutorial',
    'tutorial.skip': 'Saltar Tutorial',
    'tutorial.next': 'Siguiente',
    'tutorial.prev': 'Anterior',
    'tutorial.finish': 'Finalizar',
    'tutorial.step': 'Paso',
    'tutorial.of': 'de',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'es' ? 'es' : 'en') as Language;
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
